---
kind: pipeline
type: docker
name: node

platform:
  os: linux
  arch: amd64

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
    - name: cache
      path: /cache
    settings:
      restore: true
      mount:
        - node_modules
  - name: greeting
    image: node:8
    environment:
      JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
    commands:
      - yarn install
      - mkdir -p test-results/jest
      - yarn run test
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
    - name: cache
      path: /cache
    settings:
      rebuild: true
      mount:
        - node_modules
volumes:
  - name: cache
    host:
      path: /tmp/caches

----
kind: pipeline
type: exec
name: macos

platform:
  os: darwin
  arch: amd64
depends_on:
  - node
steps:
  - name: setup
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
      - echo "ruby-2.4" > ~/.ruby-version
  - name: debug
    commands:
      - system_profiler SPSoftwareDataType
      - env
  - name: yarn
    environment:
      NVM_DIR: /Users/cristian.pop/.nvm
    commands:
      - chmod +x $NVM_DIR/nvm.sh && $NVM_DIR/nvm.sh
      - $NVM_DIR/nvm.sh use v8.17.0
      - $NVM_DIR/nvm.sh alias default v8.17.0
      - npm install -g yarn
      - yarn install
  - name: bundle
    commands:
      - cd ios
      - brew install watchman
      - bundle install
      - bundle exec fastlane test


