
---
kind: pipeline
type: exec
name: macos

platform:
  os: darwin
  arch: amd64

steps:
  - name: setup ruby
    commands:
      - echo "ruby-2.4" > ~/.ruby-version
  - name: yarn
    commands:
      - system_profiler SPSoftwareDataType
      - env
      - nvm use 8.0
      - yarn install --cache-folder .cache/yarn
  - name: bundle
    commands:
      - cd ios
      - bundle install


