----
kind: pipeline
type: exec
name: macos

platform:
  os: darwin
  arch: amd64
#depends_on:
#  - node
steps:
  - name: setup
    commands:
      #- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
      #- export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      - echo "ruby-2.4" > ~/.ruby-version
  - name: debug
    commands:
      - system_profiler SPSoftwareDataType
      - env
  - name: yarn
    environment:
      #NVM_DIR: /Users/cristian.pop/.nvm
    commands:
      - nvm use v8.17.0
      - nvm alias default v8.17.0
      - npm install -g yarn
      - yarn install
  - name: bundle
    commands:
      - cd ios
      - brew install watchman
      - bundle install
      - bundle exec fastlane test


